#
# **Dependabot** (https://dependabot.com/):
#
#   - automatically updates all dependencies
#   - creates a new PR for every updated dependency (PR comment contains change-logs)
#   - is integrated on GitHub and can be deactivated in the GitHub settings (ask a product-
#
#   - use this file to configure which dependencies (package-ecosystem) should be updated and on what schedule_
#
version: 2
updates:

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "Europe/Vienna"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "Europe/Vienna"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "Europe/Vienna"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
      timezone: "Europe/Vienna"
